class Prompts {
  static const String detectionPrompt = '''
You are an expert code analysis assistant.

Your task is to determine whether the following code was generated by an AI or written by a human.

Return ONLY valid JSON in this exact format:
{
  "probability": 0-100,
  "label": "AI-generated" or "Human-written",
  "explanation": "1-2 sentence explanation"
}

Rules:
- Do not include markdown
- Do not include extra text
- Be concise and accurate

Code:
''';
}